[workspace]
members = [
    "parametric",
    "parametric_derive",
]
resolver = "2"

[workspace.dependencies]
proc-macro2 = { version = "1.0.101", default-features = false }
quote = { version = "1.0.40", default-features = false }
syn = { version = "2.0.106", default-features = false }
